# Generated by Django 4.1.7 on 2023-04-29 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import puppetshowapp.constants
import puppetshowapp.models.data_models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordPointingUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("login_username", models.CharField(max_length=25, unique=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("discord_snowflake", models.CharField(max_length=25, unique=True)),
                ("discord_username", models.CharField(max_length=30)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("discord_auth_token", models.CharField(max_length=100)),
                ("discord_refresh_token", models.CharField(max_length=100)),
                ("discord_avatar", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DiscordData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_snowflake", models.CharField(max_length=20)),
                ("user_username", models.CharField(max_length=100)),
                ("user_discriminator", models.CharField(max_length=4)),
                (
                    "profile_picture",
                    models.ImageField(
                        upload_to=puppetshowapp.models.data_models.user_pfp_path
                    ),
                ),
            ],
            options={
                "db_table": "discord_user_data",
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scene_name", models.CharField(max_length=30)),
                (
                    "scene_settings",
                    models.JSONField(
                        default=puppetshowapp.constants.DEFAULT_SCENE_SETTINGS
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "scene_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scenes",
            },
        ),
        migrations.CreateModel(
            name="Performer",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("discord_snowflake", models.CharField(max_length=25)),
                ("discord_username", models.CharField(max_length=30)),
                ("discord_avatar", models.URLField()),
                (
                    "settings",
                    models.JSONField(
                        default=puppetshowapp.constants.DEFAULT_PERFORMER_SETTINGS
                    ),
                ),
                (
                    "parent_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outfit",
            fields=[
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("outfit_name", models.CharField(max_length=30)),
                (
                    "settings",
                    models.JSONField(
                        default=puppetshowapp.constants.DEFAULT_OUTFIT_SETTINGS
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puppetshowapp.performer",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puppetshowapp.scene",
                    ),
                ),
            ],
            options={
                "db_table": "charactor_actors",
            },
        ),
        migrations.CreateModel(
            name="Animation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animation_type",
                    models.CharField(
                        choices=[
                            ("START_SPEAKING", "Start Speaking"),
                            ("STOP_SPEAKING", "Not Speaking"),
                            ("SLEEPING", "Sleeping"),
                            ("CONNECTION", "Connection"),
                            ("DISCONNECTION", "Disconnect"),
                        ],
                        max_length=30,
                    ),
                ),
                ("animation_path", models.URLField()),
                (
                    "outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puppetshowapp.outfit",
                    ),
                ),
            ],
            options={
                "db_table": "animations",
            },
        ),
    ]
