# Generated by Django 4.1.7 on 2023-04-28 20:08

from django.db import migrations, models
import puppetshowapp.constants


class Migration(migrations.Migration):
    dependencies = [
        ("puppetshowapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="performer",
            name="settings",
            field=models.JSONField(
                default=puppetshowapp.constants.DEFAULT_PERFORMER_SETTINGS
            ),
        ),
    ]
