# Generated by Django 4.1.7 on 2023-05-01 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("puppetshowapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animation",
            name="identifier",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
