# Generated by Django 4.1.7 on 2023-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puppetshowapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordpointinguser",
            name="discord_username",
            field=models.CharField(default="oldvalue", max_length=30),
            preserve_default=False,
        ),
    ]
