# Generated by Django 4.1.7 on 2023-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puppetshowapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discordpointinguser",
            name="rest_auth_token",
        ),
        migrations.AlterField(
            model_name="discordpointinguser",
            name="discord_avatar",
            field=models.CharField(max_length=100),
        ),
    ]
