# Generated by Django 4.1.7 on 2023-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puppetshowapp", "0002_discordpointinguser_discord_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordpointinguser",
            name="discord_avatar",
            field=models.URLField(blank=True, null=True),
        ),
    ]
