# Generated by Django 4.1.7 on 2023-05-01 18:49

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Animation = apps.get_model("puppetshowapp", "Animation")
    for animation in Animation.objects.all():
        animation.identifier = uuid.uuid4()
        animation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("puppetshowapp", "0002_animation_identifier"),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
