# Generated by Django 4.1.7 on 2023-05-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puppetshowapp", "0003_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animation",
            name="identifier",
            field=models.UUIDField(editable=False, unique=True),
        )
    ]
