from django.core.management.base import BaseCommand, CommandError
from puppetshowapp.models import DiscordPointingUser, DiscordData
from getpass import getpass


class Command(BaseCommand):
    help = "Creates a superuser with a Discord-Pointing Account."

    def add_arguments(self, parser) -> None:
        return super().add_arguments(parser)

    def handle(self, *args, **options):
        while True:
            discord_id = input("Discord Data snowflake: ")
            if DiscordData.objects.filter(user_snowflake=discord_id).exists():
                discord_data = DiscordData.objects.get(user_snowflake=discord_id)
                break
            while True:
                response = input(
                    "No Discord Data found with that snowflake. Make one? (y/n): "
                )
                if response.lower() in ("y", "n"):
                    break
            if response.lower() == "y":
                discord_data = DiscordData.objects.create(
                    user_snowflake=discord_id, user_username="Autogenerated Superuser"
                )
                break
        while True:
            password1 = getpass()
            password2 = getpass("Password (again): ")
            if password1 == password2:
                break
            self.stdout.write(self.style.ERROR("Passwords don't match."))

        user = DiscordPointingUser.objects.create_superuser(password1, discord_data)
        self.stdout.write(self.style.SUCCESS("Superuser created."))
